version: '3.2'
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    env_file:
            mongodb.env
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/dev.archive:/Databases/dev.archive
      - ./data/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    env_file:
        mongo-express.env
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"